### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by 77QingLiu** [mudassir0909/jsonresume-theme-elegant#97]
Hi,
I really like this theme, but all icons are missing in the generated HTML.
I don't know what has caused this issue. have tried both `json-resume-cli` and `hackmyresume` but both not working.
![image](https://user-images.githubusercontent.com/32193271/37871593-db7cbb9a-3023-11e8-9123-cb50b3e73ea6.png)

**Comment by nvangiessel** [comment]
Having the same issue. Grunt serve works fine, but while exporting a HTML file, icons missing.

**Comment by mudassir0909** [comment]
Sorry was busy due to other commitments, shall take a look tonight, thanks for raising the issue.

**Comment by mudassir0909** [comment]
I see the issue here, the assumption was that you wouldn't open the HTML using the `file://` protocol, i.e. if you goto the folder where the html is exported & run

```
$ python -m SimpleHTTPServer // Maybe a node server or any other static server 
```

and then visit `localhost:8000/resume.html` you should be able to load the icons. If you wish to load this on your Github pages or something then it's going to work too. It's only when you try to open the HTML using the `file://` protocol is why this fails, for such reasons you could use @nvangiessel's suggestion.

I put it `//unpkg.com` to keep it protocol independent, right now it tries to do `file://unpkg.com` which would throw a 404. Hope this helps

**Comment by 77QingLiu** [comment]
@mudassir0909 , Thanks for your kindly explanation. I'll close this issue.

**Comment by philthynz** [comment]
I have this same issue, using `json-resume-cli` and `sudo npm install -g jsonresume-theme-elegant` to install the theme. I can generate an html locally and then run `$ python -m SimpleHTTPServer` with `localhost:8000/resume.html` to see the icons. But this doesn't work for pdf exports. using something like `resume export -F --format pdf --theme elegant-custom test.pdf`

Any fix for pdf's?

**Comment by mudassir0909** [comment]
By the way, I had forgot to mention that if you're looking for a PDF version, I usually open the theme in the website format **on Google Chrome** after publishing it.

And hit `CMD/CTRL + P` to print it as PDF. I tried to optimise it for the print as much as possible, see [print.less](https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/assets/less/print.less). 

cc @philthynz

**Comment by philthynz** [comment]
@mudassir0909  Yes this works fine, and provides mostly the same format. Plus, from Chrome you can scale the output :smile:
